# Generated by Django 4.0.5 on 2022-09-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AspirantesMaestria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requisito',
            new_name='Documento',
        ),
    ]
