# Generated by Django 4.0.5 on 2022-09-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AspirantesMaestria', '0003_rename_detallerequisito_detalledocumento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalledocumento',
            old_name='requisito',
            new_name='documento',
        ),
    ]
