# Generated by Django 4.0.5 on 2022-09-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AspirantesMaestria', '0005_alter_encuesta_detalleentrevista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='requisito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitodocumento', to='AspirantesMaestria.requisito'),
        ),
    ]
