# Generated by Django 4.0.5 on 2022-09-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AspirantesMaestria', '0006_requisito_documento_requisito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstatusRequisitoEstudiante',
            new_name='EstatusRequisitoAspirantes',
        ),
    ]
