# Generated by Django 4.0.5 on 2022-10-14 19:35

import AlumnosMaestria.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidopaterno', models.CharField(max_length=45)),
                ('apellidomaterno', models.CharField(max_length=45)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('NumeroControl', models.CharField(max_length=15, unique=True)),
                ('ruta', models.FileField(upload_to=AlumnosMaestria.models.user_directory_path)),
                ('Usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnousuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(null=True, upload_to=AlumnosMaestria.models.user_directory_path)),
                ('observaciones', models.CharField(blank=True, max_length=95, null=True)),
                ('carga', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusRequisitoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=85)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=600, null=True)),
                ('catalogorequisito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.catalogorequisito')),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=600, null=True)),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=4)),
                ('detalle', models.ManyToManyField(through='AlumnosMaestria.DetalleDocumento', to='AlumnosMaestria.alumno')),
                ('requisito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitodocumento', to='AlumnosMaestria.requisito')),
            ],
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.documento'),
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='estatusrequisitoalumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.estatusrequisitoalumno'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumnosemestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='AlumnosMaestria.semestre'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnoperiodo', to='AlumnosMaestria.periodo'),
        ),
    ]
