# Generated by Django 4.0.5 on 2022-10-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumnosMaestria', '0017_alter_alumno_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='ruta',
        ),
    ]
