# Generated by Django 4.0.5 on 2022-10-14 19:43

import AlumnosMaestria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumnosMaestria', '0018_remove_alumno_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='perfil',
            field=models.FileField(default='', upload_to=AlumnosMaestria.models.user_directory_path),
            preserve_default=False,
        ),
    ]
