# Generated by Django 4.0.5 on 2022-10-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumnosMaestria', '0022_alter_alumno_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='perfil',
        ),
    ]
